ChatApp/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace ChatApp.ViewModels
{
    public class Login

    {

        [Key]
        [Required]
        [DataType(DataType.Text)]
        public string UserName { get; set; }

        

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public bool RememberMe { get; set; }
    }
}

ChatApp/ViewModels/Rcc.cs
using System.ComponentModel.DataAnnotations;
namespace ChatApp.ViewModels
{
    public class Rcc
    {
        [Key]
        public int RccId { get; set; }
        public int RccDetailId { get; set; }

        [Display(Name ="Fecha")]
        [DataType(DataType.Date)]
        public string? RCCDate { get; set; }
        
        [Display(Name = "Cuenta")]
        public int account { get; set; }


        [Display(Name ="Total Equipo")]
        public decimal EquipmentTotal { get; set; }

        [Display(Name ="Total Servicio")]
        public decimal ServiceTotal { get; set; }

        [Display(Name = "Total empresa")]
        public decimal CompanyTotal { get; set; }

        public ICollection<RccDetail> RccDetails { get; set; }

    }
}

ChatApp/ViewModels/RccDetail.cs
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace ChatApp.ViewModels
{
    public class RccDetail
    {
        [Key]
        public int RccDetailId { get; set; }       

        public Guid CollaboratorId { get; set; }

        [Required]
        [Display(Name ="Linea")]
        [StringLength(10, ErrorMessage ="Debe contener 10 nùmeros")]
        [DataType(DataType.PhoneNumber)]
        public string? Phoneline { get; set; }

          [Display(Name ="Valor Servicio")]
        public int ValueServices { get; set; }

        [Display(Name = "Valor Equipo")]
        [Required]
        public int ValueDevices { get; set; }

        public int Fee { get; set; }


        public int TotalFee { get; set; }

        [Display(Name = "Descipcion")]
        public string? Description { get; set; }

        [Display(Name = "Pagado Por: ")]
        [Required]
        public bool PaidBy { get; set; }

        public decimal Subsidy { get; set; }

        public short Group { get; set; }

        public short CICollaborator { get; set; }

        
    }
}

ChatApp/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;

namespace ChatApp.ViewModels
{
    public class Register
    {
        [Required]
        [DataType(DataType.Text)]
        public string UserName { get; set; }


        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage ="Password and confirmation did not match")]
        public string ConfirmPassword { get; set; }
    }
}

ChatApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ChatApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ChatApp/Pages/Index.cshtml.cs
using ChatApp.ViewModels;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace ChatApp.Pages
{

    public class IndexModel : PageModel
    {

        private readonly ChatApp.Data.DataContext _context;
        
        public IndexModel(ChatApp.Data.DataContext context)
        {
            _context = context;
        }

        public IList<Rcc> Rcc { get; set; }    

        public async Task OnGetAsync()
        {
            Rcc = await _context.Rccs.ToListAsync();
        }

        
        
    }
}

ChatApp/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ChatApp.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace ChatApp.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        [BindProperty]
        public Login Model { get; set; }



        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        //por convencion viene aqui cuando se esta llamando con el metodo get
        public void OnGet()
        {
        }

        //por convencion viene aqui cuando se esta llamando con el metodo post
        public async Task<IActionResult> OnPostAsync(string ?returnUrl1 = null)
        {
            if (ModelState.IsValid)
            {
                var IdentityResult = await NewMethod();
                if (IdentityResult.Succeeded)
                {
                    if (returnUrl1 == null || returnUrl1 == "/")
                    {
                        return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl1);

                    }
                }
                ModelState.AddModelError("", "Incorrect username or password");
            }
            return Page();
        }

        private Task<Microsoft.AspNetCore.Identity.SignInResult> NewMethod()
        {
            return _signInManager.PasswordSignInAsync(Model.UserName, Model.Password, Model.RememberMe, false);
        }
    }


}

ChatApp/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChatApp.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }      

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public IActionResult OnPostDontLogout()
        {           
            return RedirectToPage("Index");
        }
    }
}

ChatApp/Pages/RccDetailList.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ChatApp.Data;
using ChatApp.ViewModels;

namespace ChatApp.Pages
{
    public class RccDetailListModel : PageModel
    {
        private readonly ChatApp.Data.DataContext _context;

        public RccDetailListModel(ChatApp.Data.DataContext context)
        {
            _context = context;
        }

        public IList<RccDetail> RccDetail { get;set; }

        public async Task OnGetAsync()
        {
            RccDetail = await _context.RccDetails.ToListAsync();
        }
    }
}

ChatApp/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ChatApp.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace ChatApp.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        [BindProperty]//sin esto no coge el modelo
        public Register Model { get; set; }

        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = Model.UserName,
                    Email = Model.Email
                };
                var result = await _userManager.CreateAsync(user, Model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToPage("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return Page();
        }

    }
}

ChatApp/Pages/Index.cshtml
@page
@model ChatApp.Pages.IndexModel
@{
    ViewData["Title"] = "Welcome to the Chat App";
}

<div class="text-center">
    <h1 class="display-4">RCC</h1>

</div>

<script>
    $('#exampleModal').on('shown.bs.modal', function () {
      $('#myInput').trigger('focus')
    })

</script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<div class="counter">
    <div class="box">
        <div class="row">

            <div class="col-md-4">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Add
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Cuenta RCC</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form>
                                    <div class="form-group">
                                        <label for="recipient-name" class="col-form-label">Recipient:</label>
                                        <input type="text" class="form-control" id="recipient-name">
                                    </div>
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label">Message:</label>
                                        <textarea class="form-control" id="message-text"></textarea>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary">Send message</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div>
            <br />
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Rcc[0].RccId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Rcc[0].account)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Rcc[0].RCCDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Rcc[0].ServiceTotal)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Rcc)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.RccId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.account)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RCCDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ServiceTotal)
                            </td>
                            <td>
                                <a asp-page="./Edit" asp-route-i="@item.RccId">Edit</a> |
                                <a asp-page="./Details" asp-route-i="@item.RccId">Details</a> |
                                <a asp-page="./Delete" asp-route-i="@item.RccId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>


</div>

ChatApp/Pages/Login.cshtml
@page
@model ChatApp.Pages.LoginModel
@{
    
}


<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.UserName"> User</label>
                    <input type="text" class="form-control" asp-for="Model.UserName" placeholder="Enter UserName">
                    <span class="text-danger" asp-validation-for="Model.UserName"></span>           
                </div>
           
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password"> Password</label>
                    <input type="password" class="form-control" asp-for="Model.Password" placeholder="Enter password">
                    <span class="text-danger" asp-validation-for="Model.Password"></span>           
                </div>                
                <div class="mb-3 form-check">
                    <input type="checkbox" asp-for="Model.RememberMe" class="form-check-input" />
                    <label class="form-check-label" asp-for="Model.RememberMe">Remember me?</label>                    
                </div>
                <div class="mb-3">
                   <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
    </div>

ChatApp/Pages/Logout.cshtml
@page
@model ChatApp.Pages.LogoutModel
@{
}
<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Are you sure you want to log out</p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light m-lg-5 border-dark"  asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

ChatApp/Pages/RccDetailList.cshtml
@page
@model ChatApp.Pages.RccDetailListModel

@{
    ViewData["Title"] = "RccDetailList";
}

<h1>RccDetailList</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].CollaboratorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].Phoneline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].ValueServices)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].ValueDevices)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].Fee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].TotalFee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].PaidBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].Subsidy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].Group)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RccDetail[0].CICollaborator)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.RccDetail) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CollaboratorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phoneline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValueServices)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValueDevices)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalFee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaidBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subsidy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CICollaborator)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.RccDetailId">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.RccDetailId">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.RccDetailId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ChatApp/Pages/Register.cshtml
@page
@model ChatApp.Pages.RegisterModel
@{
   
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.UserName"> User</label>
                    <input type="text" class="form-control" asp-for="Model.UserName" placeholder="Enter UserName">
                    <span class="text-danger" asp-validation-for="Model.UserName"></span>           
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Email"> Email Address</label>
                    <input type="text" class="form-control" asp-for="Model.Email" placeholder="Enter email">
                    <span class="text-danger" asp-validation-for="Model.Email"></span>           
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password"> Password</label>
                    <input type="password" class="form-control" asp-for="Model.Password" placeholder="Enter password">
                    <span class="text-danger" asp-validation-for="Model.Password"></span>           
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.ConfirmPassword">Confirm Password</label>
                    <input type="password" class="form-control" asp-for="Model.ConfirmPassword" placeholder="Enter password">
                    <span class="text-danger" asp-validation-for="Model.ConfirmPassword"></span>           
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

ChatApp/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChatApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChatApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ChatApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Chat">Chat</a>
                                </li>
                               @* <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                                </li>*@
                                
                            </ul>
                            <ul class="navbar-nav justify-content-end ">
                                 <li class="nav-item justify-content-end">
                                    <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav flex-grow-1 justify-content-end">
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-area="" asp-page="/Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn" asp-area="" asp-page="/Register">Register</a>
                                </li>
                            </ul>
                        }              

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ChatApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>